apiVersion: v1
kind: Service
metadata:
  name: platformnpservice-srv
spec:
  type: NodePort
  selector:
    app: platformservice
  ports:
    - name: platformservice
      protocol: TCP
      port: 80 # node port internal port
      targetPort: 8080 # container port of platformservice
      nodePort: 30000 # external port to access the service